communities/urls.py
from django.urls import path, include
from communities import views

app_name = "communities"

urlpatterns = [
    path("", views.FeedListView.as_view(), name="feed"),
    path("write/", views.FeedWriteView_S.as_view(), name="write"),
    path("<int:pk>/", views.FeedDetailView.as_view(), name="feed_detail"),
    path("<int:pk>/edit", views.FeedUpdateView.as_view(), name="edit"),
    path("<int:pk>/delete", views.feedDelete, name="delete"),
    path("<int:pk>/reply", views.replyCreateView, name="reply_create"),
    path("<int:pk>/reply/<int:r_pk>", views.replyDeleteView, name="reply_delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("user/", include("users.urls", namespace="users")),
    path("virtualpool/", include("virtualpools.urls", namespace="virtualpools")),
    path("partsmarket/", include("partsmarkets.urls", namespace="partsmarkets")),
    path("community/", include("communities.urls", namespace="communities")),
    path("summernote/", include("django_summernote.urls")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core import views

app_name = "core"

urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "verify/<str:key>/",
        views.complete_verification,
        name="complete_verification",
    ),
    path("service/<str:service>", views.service_exp),
]

partsmarkets/urls.py
from django.urls import path
from partsmarkets import views

app_name = "partsmarkets"

urlpatterns = [
    path("", views.PartsMarketView.as_view(), name="partsmarket"),
    path("myproduct/", views.PartsMarketMyListView.as_view(), name="mylist"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/edit", views.PartsMarketEditView.as_view(), name="edit"),
    path("<int:pk>/delete", views.partsMarketDeleteView, name="delete"),
]

users/urls.py
from django.urls import path
from users import views

app_name = "users"

urlpatterns = [
    path("account/", views.AccountUpdateView.as_view(), name="account"),
    path("update-password", views.UpdatePasswordView.as_view(), name="password"),
]

virtualpools/urls.py
from django.urls import path
from virtualpools import views

app_name = "virtualpools"

urlpatterns = [
    path("", views.VirtualPoolView.as_view(), name="virtualpool"),
    path("<int:pk>/", views.virtualpoolDetailView, name="detail"),
    path("register/", views.virtualPoolCreateView, name="create"),
    path("addmanufacturer/", views.addManufacturer, name="addManuf"),
    path("<int:pk>/edit", views.VirutalPoolEditView.as_view(), name="edit"),
    path("<int:pk>/delete", views.virtualPoolDeleteView, name="delete"),
]

templates/partials/footer.html
<div>
    <p>
        &copy; 2022 H&A Co., Ltd. All rights reserved.
    </p>
</div>

templates/partials/header.html
<header>

    <a href="/">One-Parts</a>
    <a href="#">Virtual Pool</a>
    <a href="#">Parts Market</a>
    <a href="#">Community</a>
    <a href="#">Log in</a>
    <a href="#">Sign up</a>

</header>

templates/partials/messages.html
{% if messages%}
<ul class="absolute mx-auto top-0 left-0 right-0 flex justify-center">
    {% for message in messages %}
    <li
        class="message z-10 font-medium bg-gray-700 rounded-full text-white py-4 px-6 w-auto text-center {% if message.tags %} {{ message.tags }} {% endif %}">
        {{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

templates/partials/nav.html
{% load static %}
<a href="/" class="w-1/6 "><img class="w-20" src="{% static 'img/logo.png' %}"></a>
<ul class="flex w-2/3 justify-center">
    <li class="nav_link"><a href="{%url 'virtualpools:virtualpool'%}">Virtual
            Pool</a>
    </li>
    <li class="nav_link"><a href="{%url 'partsmarkets:partsmarket'%}">Parts Market</a></li>
    <li class="nav_link"><a href="{%url 'communities:feed'%}">Community</a></li>
</ul>
<ul class="flex w-1/6 justify-evenly text-sm font-medium">
    {% if user.is_authenticated %}
    <li class="nav_link"><a href="{%url 'users:account'%}">Account</a></li>
    <li class="nav_link"><a href="{%url 'core:logout'%}">Log out</a></li>
    {% else %}
    <li class="nav_link"><a href="{%url 'core:login'%}">Log in</a></li>
    <li class="nav_link"><a href="{%url 'core:signup'%}">Sign up</a></li>
    {% endif %}
</ul>

templates/partials/no_result.html
<div class="text-6xl text-red-600 text-center">
    <span class="align-middle">There is no result!</span>
</div>

templates/partials/product_card.html
<div class="w-1/4 mb-10 px-2">
    <a href="{% url 'partsmarkets:detail' product.pk %}">
        <div class="w-full h-64 bg-cover bg-center rounded-lg mb-2"
            style="background-image: url({{product.first_photo}})">
        </div>
        <div class="flex h-8 items-center justify-between text-sm">
            <div class="w-1/2">
                {% if product.new_part %}
                <span class="uppercase font-medium text-xs border border-black text-black rounded py-1 px-1">
                    unused
                </span>
                {% endif %}
            </div>
            <div class="w-1/2 truncate">
                {{product.maker}}
            </div>
        </div>
        <div class="truncate">
            <span>{{product.product_name}}</span><br />
            <span>{{product.model_name}}</span>
        </div>
    </a>
</div>