communities/urls.py
from django.urls import path, include
from communities import views

app_name = "communities"

urlpatterns = [
    path("", views.FeedListView.as_view(), name="feed"),
    path("write/", views.FeedWriteView_S.as_view(), name="write"),
    path("<int:pk>/", views.FeedDetailView.as_view(), name="feed_detail"),
    path("<int:pk>/edit", views.FeedUpdateView.as_view(), name="edit"),
    path("<int:pk>/delete", views.feedDelete, name="delete"),
    path("<int:pk>/reply", views.replyCreateView, name="reply_create"),
    path("<int:pk>/reply/<int:r_pk>", views.replyDeleteView, name="reply_delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("user/", include("users.urls", namespace="users")),
    path("virtualpool/", include("virtualpools.urls", namespace="virtualpools")),
    path("partsmarket/", include("partsmarkets.urls", namespace="partsmarkets")),
    path("community/", include("communities.urls", namespace="communities")),
    path("summernote/", include("django_summernote.urls")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core import views

app_name = "core"

urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "verify/<str:key>/",
        views.complete_verification,
        name="complete_verification",
    ),
    path("service/<str:service>", views.service_exp),
]

communities/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from core.models import TimeStampedModel

DEFAULT_PK = 45


class Feed(TimeStampedModel):
    """Feed Model Defenition"""

    writer = models.ForeignKey(
        "users.User",
        on_delete=models.CASCADE,
        # default=DEFAULT_PK,
        verbose_name=_("writer"),
    )
    content = models.TextField(_("content"))
    attach = models.FileField(
        _("attachment"),
        upload_to="uploads/",
        blank=True,
    )

    def count_reply(self):
        return self.reply_set.count()

    count_reply.short_description = _("#Reply")

    def __str__(self):
        return f"{self.writer}-{self.content[:40]}"

    def get_absolute_url(self):

        return reverse("communities:feed_detail", kwargs={"pk": self.pk})


class Reply(TimeStampedModel):
    """Reply Model Defenition"""

    original_feed = models.ForeignKey("Feed", on_delete=models.CASCADE)
    # 향후, 탈퇴하더라도 댓글은 지워지지 않고, 최종 닉네임이 남도록 한다
    writer = models.ForeignKey(
        "users.User", on_delete=models.SET_NULL, null=True, verbose_name=_("writer")
    )
    content = models.TextField(_("content"))

    def __str__(self):
        return f"{self.writer}-{self.content[:40]}"

communities/forms.py
from django import forms
from django_summernote.fields import SummernoteTextField
from django_summernote.widgets import SummernoteWidget
from .models import Feed


class FeedWriteForm(forms.ModelForm):

    # content = SummernoteTextField()

    class Meta:
        model = Feed
        fields = [
            "writer",
            "content",
            "attach",
        ]
        widgets = {"content": SummernoteWidget()}

    # def clean(self):
    #     cleaned_data = super().clean()
    #     contents = cleaned_data.get("content", "")

    #     if contents == "":
    #         self.add_error("content", "Input your contents")

communities/views.py
import json
from django.urls import reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, FormView
from django.db.models import Q
from django.contrib import messages
from django.http import JsonResponse
from psycopg2 import IntegrityError
from core.mixins import OnlyForMember
from .models import *
from .forms import FeedWriteForm

# Create your views here.
class FeedListView(ListView):
    model = Feed
    paginate_by = 20
    paginate_orphans = 12
    ordering = ["-created"]

    def get_queryset(self):
        queryset = super().get_queryset()
        search = self.request.GET.get("search")
        if search is not None:
            queryset = queryset.filter(
                Q(writer__username__contains=search) | Q(content__contains=search)
            )
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        search = self.request.GET.get("search")
        if search:
            context["input"] = search
        return context


class FeedDetailView(OnlyForMember, DetailView):
    model = Feed
    fields = (
        "writer",
        "content",
        "created",
    )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs["pk"]
        replies = Reply.objects.filter(original_feed=pk)
        context["replies"] = replies
        return context


def feed_write(request):
    context = {}
    if request.method == "GET":
        write_form = FeedWriteForm()
        context["form"] = write_form
        return render(request, "communities/feed_create.html", context)
    elif request.method == "POST":
        write_form = FeedWriteForm(request.POST)
        return redirect("communities:feed")


class FeedWriteView_S(FormView):
    form_class = FeedWriteForm
    template_name = "communities/feed_create.html"
    success_url = reverse_lazy("communities:feed_detail")

    def form_valid(self, form):
        item = form.save()
        self.pk = item.pk
        return super().form_valid(form)

    def get_success_url(self) -> str:
        print(self.pk)
        return reverse("communities:feed_detail", kwargs={"pk": self.pk})


class FeedCreateView(OnlyForMember, CreateView):
    model = Feed
    fields = (
        "writer",
        "content",
        "attach",
    )
    template_name = "communities/feed_create.html"


class FeedUpdateView(UpdateView):
    model = Feed
    fields = (
        "content",
        "attach",
    )
    template_name = "communities/feed_create.html"


def feedDelete(request, pk):
    user = request.user
    try:
        feed = Feed.objects.get(pk=pk)
        if feed.writer.pk != user.pk:
            messages.success(request, "Can't Deleted")
        else:
            result = feed.delete()
            print(result)
            messages.success(request, "Feed Deleted")
    except Feed.DoesNotExist:
        messages.success(request, "It's been deleted already")
    finally:
        return redirect("communities:feed")


@csrf_exempt
def replyCreateView(request, pk):
    if request.method == "POST":
        bodydata = request.body.decode("utf-8")
        bodyjson = json.loads(bodydata)
        text = bodyjson["reply"]
        user = request.user
        original_feed = Feed.objects.get(pk=pk)
        context = {}
        try:
            new_reply = Reply.objects.create(
                original_feed=original_feed, writer=user, content=text
            )
            context["pk"] = new_reply.pk
            context["writer"] = new_reply.writer.username
            context["content"] = new_reply.content
            return JsonResponse(context, content_type="application/json")
        except IntegrityError:
            return


def replyDeleteView(request, pk, r_pk):
    user = request.user
    context = {}
    try:
        reply = Reply.objects.get(pk=r_pk)
        if reply.writer.pk != user.pk:
            context["result"] = "Can't delete"

        else:
            reply.delete()
            context["result"] = "Deleted"
    except Feed.DoesNotExist:
        context["result"] = "There is no target reply"
    finally:
        return JsonResponse(context, content_type="application/json")

templates/communities/feed_create.html
{% extends 'base.html' %}

{% block page_name %}
Write Feed
{% endblock page_name %}

{% block search-form %}
<div class="flex items-center">
    <div class="w-1/2">
        <form class="p-3 w-2/5" action="{%url 'communities:feed'%}" method="get">
            <input class="search-box placeholder-gray-600" type="text" name="search" id="search"
                placeholder="Search in Community" value={{input}}>
        </form>
    </div>
    <div class="w-1/2 flex justify-end">
        <a href="{%url 'communities:write'%}" class="h-full p-2 rounded-lg border border-blue-400 ">Write</a>
    </div>
</div>
{% endblock search-form %}

{% block content %}
<div class="w-2/3 mx-auto">
    <form method="POST" enctype="multipart/form-data">
        {%csrf_token%}
        <label>Writer</label>
        <input class="mb-3" type="text" value="{{user}}" readonly>
        <input type="hidden" value="{{user.pk}}" name="writer" id="id_writer">
        {{form.content}}

        <label>Attachment</label>
        <input class="mb-3" type="file" id="id_attach" name="attach">
        <button class="btn-link">submmit</button>
    </form>
</div>
{% endblock content %}

templates/communities/feed_detail.html
{% extends 'base.html' %}
{% load file_split%}
{% block page_name %}
Community
{% endblock page_name %}

{% block search-form %}
<div class="flex items-center">
    <div class="w-1/2">
        <form class="p-3 w-4/5" action="{%url 'communities:feed'%}" method="get">
            <input class="search-box placeholder-gray-600" type="text" name="search" id="search"
                placeholder="Search in Community" value={{input}}>
        </form>
    </div>
</div>
{% endblock search-form %}

{% block content %}
<div class="w-2/3 mx-auto">
    <p>
        Writer : {{feed.writer}}
    </p>
    <p>
        created : {{feed.created}}
    </p>
    <div class="mt-2">
        {{feed.content | safe}}
    </div>
    <div class="p-2 border border-gray-500">
        Attachment<br>
        {%if feed.attach%}
        <a href="{{feed.attach.url}}">{{feed.attach|split:"/"}}</a>
        {%else%}
        No files
        {%endif%}
    </div>
    {% include 'communities/reply_list.html' with replies=replies%}
</div>
{% if user == feed.writer %}
<div class="flex flex-col mx-auto w-1/4 text-center">
    <a class="border border-blue-600 rounded p-4 my-2" href="{%url 'communities:edit' feed.pk%}">Edit</a>
    <a class="border border-red-600 rounded p-4 my-2" href="{%url 'communities:delete' feed.pk%}">Delete</a>
</div>
{% endif %}
{% endblock content %}

templates/communities/feed_list.html
{% extends 'base.html' %}

{% block page_name %}
Community
{% endblock page_name %}

{% block search-form %}
<div class="flex items-center">
    <div class="w-1/2">
        <form class="p-3 w-4/5" action="{%url 'communities:feed'%}" method="get">
            <input class="search-box placeholder-gray-600" type="text" name="search" id="search"
                placeholder="Search in Community" value={{input}}>
        </form>
    </div>
    <div class="w-1/2 flex justify-end">
        <a href="{%url 'communities:write'%}" class="h-full p-2 rounded-lg border border-blue-400 ">Write</a>
    </div>
</div>
{% endblock search-form %}

{% block content %}
{%if object_list.all%}
<table class="container">
    <thead>
        <tr class="w-full border-b">
            <th class="w-1/12">
                <p>WRITER</p>
            </th>
            <th class="w-4/12">
                <p>CONTENTS</p>
            </th>
            <th class="w-4/12">
                <p>Num of Reply</p>
            </th>
            <th class="w-3/12">
                <p>Date</p>
            </th>
        </tr>
    </thead>
    <tbody>
        {% for feed in object_list %}
        <tr class="cursor-pointer border-b" onClick="location.href='/community/{{feed.pk}}'">
            <td class="text-center">
                <p>{{feed.writer}}</p>
            </td>
            <td class="max-w-3xl">
                <p class="truncate">{{feed.content | safe}}</p>
            </td>
            <td class="px-1 py-1">
                <p>{{feed.count_reply}}</p>
            </td>
            <td class="text-center">
                <p>{{feed.created}}</p>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{%else%}
{% include 'partials/no_result.html' %}
{%endif%}


{% include 'mixins/pagination.html' with page_obj=page_obj %}

{% endblock content %}

templates/communities/reply_list.html
<div class="mt-2">

    <table id="reply_list">
        {% for reply in replies %}
        <tr id="id_{{reply.pk}}">
            <td class="px-2">{{reply.writer}}</td>
            <td class="pl-4">{{reply.content}}</td>
            <td class="pl-4">
                {% ifequal user.username reply.writer.username %}
                <a href="javascript:deleteReply({{feed.pk}}, {{reply.pk}})" class="p-2">ⓧ</a>
                {% endifequal %}
            </td>
        </tr>
        {% endfor %}
    </table>
</div>
<div class="mt-4">
    <form class="flex flex-between" method="POST" action="javascript:createReply()">
        {%csrf_token%}
        <input class="w-full" type="text" id="reply">
        <button class="ml-2 p-2 border border-red-500">save</button>
    </form>
</div>
<script>
    function createReply() {
        var text = document.getElementById("reply").value;
        if (text === "") {
            return alert("please input text")
        }
        const data = { reply: text };
        fetch("{% url 'communities:reply_create' feed.pk %}", {
            method: 'POST',
            headers: { 'Content-Type': 'application/json; charset=UTF-8', },
            body: JSON.stringify(data),
        })
            .then((response) => {
                if (response.status != 200) {
                    return alert("Failed to save your reply");
                }
                return response.json();
            })
            .then((data) => {
                document.getElementById("reply").value = null
                var target = document.getElementById("reply_list");
                var newRow = target.insertRow(-1);
                newRow.setAttribute("id", "id_" + data['pk']);
                newRow.innerHTML = "<td class='px-2'>" + data['writer'] + "</td><td class='pl-4'>" + data['content'] + "</td><td class='pl-4'><a href='javascript:deleteReply({{feed.pk}}," + data['pk'] + ")' class='p-2'>ⓧ</a></td >"
            })
            .catch(function (err) {
                console.log('Error: ', err)
            })

    }
    function deleteReply(pk, r_pk) {
        if (confirm("Do you want to delete it?")) {
            fetch("/community/" + pk + "/reply/" + r_pk)
                .then((response) => {
                    if (response.status != 200) {
                        return alert("Failed to delete");
                    }
                    return response.json();
                })
                .then((data) => {
                    console.log(data);
                    document.getElementById("id_" + r_pk).remove()
                })
                .catch(function (err) {
                    console.log('Error: ', err)
                })
        }
    }

</script>

templates/communities/test.html
test
{{form.as_table}}