config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("user/", include("users.urls", namespace="users")),
    path("virtualpool/", include("virtualpools.urls", namespace="virtualpools")),
    path("partsmarket/", include("partsmarkets.urls", namespace="partsmarkets")),
    path("community/", include("communities.urls", namespace="communities")),
    path("summernote/", include("django_summernote.urls")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core import views

app_name = "core"

urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "verify/<str:key>/",
        views.complete_verification,
        name="complete_verification",
    ),
    path("service/<str:service>", views.service_exp),
]

virtualpools/urls.py
from django.urls import path
from virtualpools import views

app_name = "virtualpools"

urlpatterns = [
    path("", views.VirtualPoolView.as_view(), name="virtualpool"),
    path("<int:pk>/", views.virtualpoolDetailView, name="detail"),
    path("register/", views.virtualPoolCreateView, name="create"),
    path("addmanufacturer/", views.addManufacturer, name="addManuf"),
    path("<int:pk>/edit", views.VirutalPoolEditView.as_view(), name="edit"),
    path("<int:pk>/delete", views.virtualPoolDeleteView, name="delete"),
]

virtualpools/models.py
from django.urls import reverse
from django.db import models
from django.core.validators import MinValueValidator
from django.utils.translation import gettext_lazy as _
from core.models import TimeStampedModel

# 회사 이름 집합 ex) (mhi, 미쯔비시중공업, mhps) -> MPW
class OfficialMakerName(TimeStampedModel):
    """Official Maker Name Model Definition"""

    name = models.CharField(_("official company name"), max_length=30, unique=True)

    def __str__(self) -> str:
        return self.name


# 옛날 회사명
class OldMakerName(TimeStampedModel):
    """Old Maker Name Model Definition"""

    name = models.CharField(_("old manufacturer name"), max_length=30, unique=True)
    official_name = models.ForeignKey("OfficialMakerName", on_delete=models.CASCADE)


class Compatibility(TimeStampedModel):
    group = models.ManyToManyField("stock", blank=True)


# Virtual Pool 등록 상품
class Stock(TimeStampedModel):
    """Stock Information Model Definition"""

    name = models.CharField(_("stock name"), max_length=30)
    maker = models.ForeignKey(
        "OfficialMakerName",
        on_delete=models.SET_NULL,
        null=True,
        verbose_name=_("manufacturer"),
    )
    model_name = models.CharField(_("model"), max_length=30)
    spec = models.CharField(_("specification"), max_length=30, blank=True)
    # 재고품 총 갯수
    def total_stock(self):
        stockinfo_objs = self.stockinfo_set.all()
        total = 0
        for i in stockinfo_objs:
            total += i.num_stock
        return total

    def owner_info(self):
        stockinfo_objs = self.stockinfo_set.filter(num_stock__gt=0)
        owner_list = []
        for i in stockinfo_objs:
            owner_list.append(i)
        return owner_list


# Virtual Pool 사용자의 등록 정보
class StockInfo(TimeStampedModel):
    owner = models.ForeignKey(
        "users.User",
        on_delete=models.CASCADE,
        verbose_name=_("owner"),
    )
    my_stock = models.ForeignKey("Stock", on_delete=models.CASCADE)
    num_stock = models.IntegerField(
        _("num of stocks"), validators=[MinValueValidator(0)]
    )
    place = models.CharField(_("using place"), max_length=30)
    is_new = models.BooleanField(_("new part"))
    contact_person = models.CharField(_("person in charge"), max_length=20, blank=True)
    contact_info = models.CharField(_("contact information"), max_length=30, blank=True)

    def get_absolute_url(self):
        return reverse("virtualpools:detail", kwargs={"pk": self.pk})

virtualpools/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from virtualpools.models import Stock, StockInfo


class CreateStockForm(forms.ModelForm):
    class Meta:
        model = Stock
        fields = (
            "name",
            "maker",
            "model_name",
            "spec",
        )


class CreateStockInfoForm(forms.ModelForm):
    class Meta:
        model = StockInfo
        fields = (
            "num_stock",
            "place",
            "is_new",
            "contact_person",
            "contact_info",
        )

virtualpools/views.py
import json
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.mixins import UserPassesTestMixin
from django.views.generic import ListView, DetailView, UpdateView
from django.shortcuts import render, redirect, reverse
from django.db.models import Q
from django.db import IntegrityError
from django.contrib import messages
from django.http import Http404, HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required
from core.mixins import OnlyForMember, OnlyForVerifiedMember
from . import models, forms


# 회사인증이 완료된 사람만 조회가능
# 로그인/리스트나 reservation을 배워야 할 듯
class VirtualPoolView(OnlyForVerifiedMember, ListView):
    model = models.StockInfo
    paginate_by = 10
    paginate_orphans = 5
    ordering = "created"

    def get_queryset(self):
        pk = self.request.user.pk
        queryset = super().get_queryset()
        search = self.request.GET.get("search")
        if search is not None:
            queryset = queryset.filter(
                Q(owner=pk),
                (
                    Q(my_stock__name__contains=search)
                    | Q(my_stock__maker__name__contains=search)
                    | Q(my_stock__model_name__contains=search)
                ),
            )
        else:
            queryset = queryset.filter(owner=pk)
        return queryset

    # 검색어 창에 검색어를 남기고, 검색결과에 대한 pagination을 위해 context를 추가
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        search = self.request.GET.get("search")
        if search:
            context["input"] = search
        return context


@login_required(login_url="core:login")
def virtualpoolDetailView(request, pk):
    try:
        stockinfo = models.StockInfo.objects.get(pk=pk)
        if stockinfo.owner.pk != request.user.pk:
            messages.error(request, "You're not allow to see this parts")
            return redirect("virtualpools:virtualpool")
        else:
            return render(
                request, "virtualpools/stockinfo_detail.html", {"stockinfo": stockinfo}
            )
    except models.StockInfo.DoesNotExist:
        raise Http404()


@login_required(login_url="core:login")
def virtualPoolCreateView(request):
    if request.method == "POST":
        stock_form = forms.CreateStockForm(request.POST)
        stockinfo_form = forms.CreateStockInfoForm(request.POST)
        if stock_form.is_valid() and stockinfo_form.is_valid():
            stock_pk = stock_form.save()
            stockinfo = stockinfo_form.save(commit=False)
            stockinfo.owner = request.user
            stockinfo.my_stock = stock_pk
            stockinfo.save()
            return redirect("virtualpools:virtualpool")
        else:
            context = {
                "stock_form": stock_form,
                "stockinfo_form": stockinfo_form,
            }
    else:
        context = {
            "stock_form": forms.CreateStockForm(),
            "stockinfo_form": forms.CreateStockInfoForm(),
        }
    return render(request, "virtualpools/create.html", context)


class OnlyForOwner(UserPassesTestMixin):
    def test_func(self):
        pk = self.kwargs["pk"]
        user_pk = self.request.user.pk
        stockinfo = models.StockInfo.objects.get(pk=pk)
        if stockinfo.owner.pk != user_pk:
            return False
        else:
            return True

    def handle_no_permission(self):
        messages.error(self.request, "You're not allow to edit this part.")
        return redirect("virtualpools:virtualpool")


class VirutalPoolEditView(OnlyForOwner, UpdateView):
    model = models.StockInfo
    fields = (
        "num_stock",
        "place",
        "is_new",
        "contact_person",
        "contact_info",
    )
    template_name = "virtualpools/edit.html"


def virtualPoolDeleteView(request, pk):
    user = request.user
    try:
        stockinfo = models.StockInfo.objects.get(pk=pk)
        if stockinfo.owner.pk != user.pk:
            messages.error(request, "Can't delete!")
        else:
            stockinfo.delete()
            messages.success(request, "Stock Deleted")
        return redirect("virtualpools:virtualpool")
    except models.StockInfo.DoesNotExist:
        return redirect("virtualpools:virtualpool")


@csrf_exempt
def addManufacturer(request):
    if request.method == "POST":
        bodydata = request.body.decode("utf-8")
        bodyjson = json.loads(bodydata)
        name = bodyjson["name"].upper()
        context = {}
        try:
            new_manu = models.OfficialMakerName.objects.create(name=name)
            context["pk"] = new_manu.pk
            context["name"] = new_manu.name
            return JsonResponse(context, content_type="application/json")
        except IntegrityError as e:
            print("error :", e)
            return JsonResponse(context, content_type="application/json")

templates/virtualpools/create.html
{% extends 'base.html' %}
{% load static i18n %}
{% block page_name %}
Register
{% endblock page_name %}


{% block content %}
<div class="w-1/2 mx-auto my-4">
    <div class="flex justify-end">
        <button class="p-2 border border-red-500 rounded-lg" onclick="add_manufac()">Add Manufacturer</button>
    </div>
    <form method="POST">
        {% csrf_token %}
        {{stock_form.as_p}}
        {{stockinfo_form.as_p}}
        <button class="btn-link mt-2">submit</button>
    </form>
    <div class="my-2 p-3 rounded-lg border border-gray-500 bg-gray-500 w-full text-center">
        <a href="{% url 'virtualpools:virtualpool' %}">Back</a>
    </div>
</div>
<script>
    function add_manufac() {
        var manufac = prompt("Add a new menufacturer")
        manufac = manufac.trim()
        if (manufac !== null) {
            if (manufac === "") {
                return alert("Please input the name")
            }
            const data = { name: manufac }
            fetch("{% url 'virtualpools:addManuf' %}", {
                method: 'POST',
                headers: { 'Content-Type': 'application/json; charset=UTF-8', },
                body: JSON.stringify(data),
            })
                .then((response) => {
                    if (response.status !== 200) {
                        return alert('Can\'t register the item')
                    }
                    return response.json()
                })
                .then((data) => {
                    if (data['pk'] != null) {
                        var target = document.getElementById('id_maker');
                        var opt = document.createElement("option");
                        opt.value = data['pk'];
                        opt.innerHTML = data['name'];
                        target.appendChild(opt);
                    } else {
                        alert("Item is not registred")
                    }
                })
                .catch(function (err) {
                    console.log('Error : ', err);
                })
        }
    }
</script>
{% endblock content %}

templates/virtualpools/edit.html
{% extends 'base.html' %}
{% load static i18n %}
{% block page_name %}
Edit
{% endblock page_name %}

{% block content %}
<div class="w-1/2 mx-auto my-4">

    <p class="text-2xl text-center">{{stockinfo.my_stock.name}}</p>
    <p class="text-1xl text-center">{{stockinfo.my_stock.model_name}}</p>
    <p class="text-lg text-right">{{stockinfo.my_stock.maker}}</p>
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn-link mt-2">submit</button>
    </form>
    <div class="text-center mt-2">
        <button class="w-full py-3 border border-gray-500 rounded-lg bg-gray-500 text-white"
            onClick="location.href='{% url 'virtualpools:detail' stockinfo.pk %}'">Back</button>
    </div>
</div>
{% endblock content %}

templates/virtualpools/stockinfo_detail.html
{% extends 'base.html' %}

{% block page_name %}
Stock Detail
{% endblock page_name %}

{% block search-form %}
<div class="flex items-center">
    <div class="w-1/2">
        <form class="p-3 w-4/5" action="{%url 'virtualpools:virtualpool'%}" method="get">
            <input class="search-box placeholder-gray-600" type="text" name="search" id="search"
                placeholder="Search in Virtual Pool" value={{input}}>
        </form>
    </div>
    <div class="w-1/2 flex justify-end">
        <a href="{%url 'virtualpools:create'%}" class="h-full p-2 rounded-lg border border-blue-400 ">Register Part</a>
    </div>
</div>
{% endblock search-form %}

{% block content %}
<div>
    <table class="tbl-stock">
        <tr>
            <th>Manufacturer</th>
            <td>{{stockinfo.my_stock.maker}}</td>
        </tr>
        <tr>
            <th>Product</th>
            <td>{{stockinfo.my_stock.name}}</td>
        </tr>
        <tr>
            <th>Model</th>
            <td>{{stockinfo.my_stock.model_name}}</td>
        </tr>
        <tr>
            <th>Where to use</th>
            <td>{{stockinfo.place}}</td>
        </tr>
        <tr>
            <th>New part</th>
            <td>{{stockinfo.is_new}}</td>
        </tr>
        <tr>
            <th>Number of My Stock</th>
            <td>{{stockinfo.num_stock}}</td>
        </tr>
        <tr>
            <th>Available Stocks</th>
            <td>{{stockinfo.my_stock.total_stock}}</td>
        </tr>
        <tr>
            <th>Owner Info</th>
            <td>
                {% for a in stockinfo.my_stock.owner_info %}
                <div class="sm:flex sm:justify-between">
                    <p class="truncate">{{a.contact_person}}</p>
                    <p class="truncate">{{a.contact_info}}</p>
                </div>
                {% endfor %}
            </td>
        </tr>
    </table>
</div>
<div class="flex flex-col mx-auto w-1/4 text-center">
    <a class="border border-blue-600 rounded p-4 my-2" href="{% url 'virtualpools:edit' stockinfo.pk%}">Edit</a>
    <a class="border border-red-600 rounded p-4 my-2" href="javascript:delete_stock({{stockinfo.pk}})">Delete</a>
</div>
<script>
    function delete_stock(pk) {
        if (confirm("Are you sure to delete this item?") == false) {
            return false;
        }
        window.location.href = "{% url 'virtualpools:delete' stockinfo.pk %}";
    }
</script>
{% endblock content %}

templates/virtualpools/stockinfo_list.html
{% extends 'base.html' %}

{% block page_name %}
Virtual Pool
{% endblock page_name %}

{% block search-form %}
<div class="flex items-center">
    <div class="w-1/2">
        <form class="p-3 w-4/5" action="{%url 'virtualpools:virtualpool'%}" method="get">
            <input class="search-box placeholder-gray-600" type="text" name="search" id="search"
                placeholder="Search in Virtual Pool" value={{input}}>
        </form>
    </div>
    <div class="w-1/2 flex justify-end">
        <a href="{%url 'virtualpools:create'%}" class="h-full p-2 rounded-lg border border-blue-400 ">Register Part</a>
    </div>
</div>
{% endblock search-form %}

{% block content %}
{%if object_list.all%}
<table class="container">
    <thead>
        <tr class="w-full border-b">
            <th class="w-1/12">
                <p>STOCK</p>
            </th>
            <th class="w-4/12">
                <p>NAME</p>
            </th>
            <th class="w-4/12">
                <p>MODEL</p>
            </th>
            <th class="w-3/12">
                <p>MANUFAC.</p>
            </th>
        </tr>
    </thead>
    <tbody>
        {% for info in object_list %}
        <tr class="cursor-pointer border-b" onClick="location.href='/virtualpool/{{info.pk}}'">
            <td class="text-center">
                <p>{{info.num_stock}} / {{info.my_stock.total_stock}}</p>
            </td>
            <td class="px-1 py-1">
                <p>{{info.my_stock.name}}</p>
            </td>
            <td class="px-1 py-1">
                <p>{{info.my_stock.model_name}}</p>
            </td>
            <td class="text-center">
                <p>{{info.my_stock.maker}}</p>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% include 'mixins/pagination.html' with page_obj=page_obj %}
{%else%}
{% include 'partials/no_result.html' %}
{%endif%}

{% endblock content %}

templates/virtualpools/update.html
<p>{{stockinfo.my_stock.maker}}</p>
<p>{{stockinfo.my_stock.name}}</p>
<p>{{stockinfo.my_stock.model_name}}</p>
<form method="POST">
    {% csrf_token %}
    {%for f in form%}
    <p>{{f.label}} : {{f}}</p>
    {%endfor%}
    <button>submit</button>
</form>