config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("user/", include("users.urls", namespace="users")),
    path("virtualpool/", include("virtualpools.urls", namespace="virtualpools")),
    path("partsmarket/", include("partsmarkets.urls", namespace="partsmarkets")),
    path("community/", include("communities.urls", namespace="communities")),
    path("summernote/", include("django_summernote.urls")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core import views

app_name = "core"

urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "verify/<str:key>/",
        views.complete_verification,
        name="complete_verification",
    ),
    path("service/<str:service>", views.service_exp),
]

partsmarkets/urls.py
from django.urls import path
from partsmarkets import views

app_name = "partsmarkets"

urlpatterns = [
    path("", views.PartsMarketView.as_view(), name="partsmarket"),
    path("myproduct/", views.PartsMarketMyListView.as_view(), name="mylist"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/edit", views.PartsMarketEditView.as_view(), name="edit"),
    path("<int:pk>/delete", views.partsMarketDeleteView, name="delete"),
]

partsmarket/models.py
from django.db import models
from django.core.validators import MinValueValidator
from core.models import TimeStampedModel
from users.models import User, EquipGroup
from virtualpools.models import OfficialMakerName

# Part Market 등록 상품
class Photo(TimeStampedModel):

    """Photo Model Definition"""

    file = models.ImageField(upload_to="product_photos")
    product = models.ForeignKey("Product", on_delete=models.SET_DEFAULT, default=1)

    def __str__(self):
        return self.product.product_name


class Product(TimeStampedModel):
    seller = models.ForeignKey(User, on_delete=models.CASCADE)
    product_name = models.CharField(max_length=140)
    maker = models.ForeignKey(OfficialMakerName, on_delete=models.SET_NULL, null=True)
    model_name = models.CharField(max_length=140)
    spec = models.CharField(max_length=180, blank=True)
    description = models.TextField(blank=True)
    num_product = models.IntegerField(validators=[MinValueValidator(0)])
    new_part = models.BooleanField()
    contact_person = models.CharField(max_length=100, blank=True)
    contact_number = models.CharField(max_length=100, blank=True)
    price = models.IntegerField(validators=[MinValueValidator(1)])
    category = models.ForeignKey(EquipGroup, on_delete=models.SET_NULL, null=True)

    def seller_name(self):
        return self.seller.nickname

    seller_name.short_description = "Seller"

    def __str__(self):
        return f"'{self.maker}' / '{self.product_name}' / '{self.model_name}'"

partsmarkets/models.py
from django.urls import reverse
from django.db import models
from django.core.validators import MinValueValidator
from django.utils.translation import gettext_lazy as _
from core.models import TimeStampedModel

# Part Market 등록 상품
class Photo(TimeStampedModel):
    """Photo Model Definition"""

    file = models.ImageField(upload_to="product_photos")
    product = models.ForeignKey("Product", on_delete=models.CASCADE)

    def __str__(self):
        return str(self.file)


class Product(TimeStampedModel):
    """Product Model Definition"""

    name = models.CharField(max_length=30)
    seller = models.ForeignKey(
        "users.User", on_delete=models.CASCADE, verbose_name=_("seller")
    )
    maker = models.ForeignKey(
        "virtualpools.OfficialMakerName",
        on_delete=models.SET_NULL,
        null=True,
        verbose_name=_("manufacturer"),
    )
    model_name = models.CharField(_("model"), max_length=30)
    spec = models.CharField(_("specification"), max_length=30, blank=True)
    description = models.TextField(_("description"), blank=True)
    num_product = models.IntegerField(
        _("number of products"), validators=[MinValueValidator(0)]
    )
    is_new = models.BooleanField(_("new part"), default=True)
    contact_person = models.CharField(_("person in charge"), max_length=20, blank=True)
    contact_info = models.CharField(_("contact information"), max_length=30, blank=True)
    price = models.IntegerField(validators=[MinValueValidator(1)])
    category = models.ForeignKey(
        "users.EquipGroup",
        on_delete=models.SET_NULL,
        null=True,
    )
    on_sale = models.BooleanField(_("on sale"), blank=True, default=False)

    def get_first_photo(self):
        try:
            (photo,) = self.photo_set.all()[:1]
            return photo.file.url
        except ValueError:
            return None

    def get_photos(self):
        try:
            photos = self.photo_set.all()[:3]
            return photos
        except ValueError:
            return None

    def get_absolute_url(self):
        return reverse("partsmarkets:detail", kwargs={"pk": self.pk})

partsmarkets/views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.views.generic import ListView, DetailView, UpdateView
from django.shortcuts import render, redirect
from django.db.models import Q
from django.contrib import messages
from django.urls import reverse_lazy
from core.mixins import OnlyForVerifiedMember
from . import models


class PartsMarketView(ListView):
    model = models.Product
    paginate_by = 16
    paginate_orphans = 12
    ordring = "created"

    # 다중쿼리를 이용함으로써 검색필드를 제거함
    def get_queryset(self):
        queryset = super().get_queryset()
        search = self.request.GET.get("search")
        if search is not None:
            queryset = queryset.filter(
                Q(name__contains=search)
                | Q(maker__name__contains=search)
                | Q(model_name__contains=search)
            )
        else:
            queryset = queryset.filter(on_sale=True)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        search = self.request.GET.get("search")
        if search:
            context["input"] = search
        return context


class PartsMarketMyListView(ListView):
    model = models.Product
    paginate_by = 16
    paginate_orphans = 12
    ordring = "created"

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(seller__pk=self.request.user.pk)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        search = self.request.GET.get("search")
        if search:
            context["input"] = search
        return context


# 회사인증이 완료된 사람만 조회가능
class DetailView(OnlyForVerifiedMember, DetailView):
    model = models.Product

    login_url = reverse_lazy("core:login")


class OnlyForOwner(UserPassesTestMixin):
    def test_func(self):
        pk = self.kwargs["pk"]
        user_pk = self.request.user.pk
        product = models.Product.objects.get(pk=pk)
        if product.seller.pk != user_pk:
            return False
        else:
            return True

    def handle_no_permission(self):
        messages.error(self.request, "You're not allow to edit this product.")
        return redirect("partsmarkets:partsmarket")


class PartsMarketEditView(OnlyForOwner, UpdateView):
    model = models.Product
    fields = (
        "description",
        "num_product",
        "contact_person",
        "contact_info",
        "price",
        "on_sale",
    )
    template_name = "partsmarkets/edit.html"


def partsMarketDeleteView(request, pk):
    user = request.user
    try:
        product = models.Product.objects.get(pk=pk)
        if product.seller.pk != user.pk:
            messages.error(request, "Can't delete!")
        else:
            models.Product.objects.filter(pk=pk).delete()
            messages.success(request, "Product Deleted")
        return redirect("partsmarkets:partsmarket")
    except models.Product.DoesNotExist:
        return redirect("partsmarkets:partsmarket")

templates/partsmarkets/edit.html
{% extends 'base.html' %}
{% load static i18n %}
{% block page_name %}
Edit
{% endblock page_name %}

{% block content %}
<div class="w-1/2 mx-auto my-4">

    <p class="text-2xl text-center">{{product.name}}</p>
    <p class="text-1xl text-center">{{product.model_name}}</p>
    <p class="text-lg text-right">{{product.maker.name}}</p>
    <p class="text-lg">Specification : {{product.spec}}</p>
    <p class="text-lg">{% if product.is_new %} Unused {%else%} used {%endif%}</p>
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn-link mt-2">submit</button>
    </form>
    <div class="text-center mt-2">
        <button class="w-full py-3 border border-gray-500 rounded-lg bg-gray-500 text-white"
            onClick="location.href='{% url 'partsmarkets:detail' product.pk %}'">Back</button>
    </div>
</div>

{% endblock content %}

templates/partsmarkets/product_detail.html
{% extends 'base.html' %}

{% block page_name %}
Virtual Pool
{% endblock page_name %}

{% block search-form %}
<div class="flex items-center">
    <div class="w-1/2">
        <form class="p-3 w-4/5" action="{%url 'partsmarkets:partsmarket'%}" method="get">
            <input class="search-box placeholder-gray-600" type="text" name="search" id="search"
                placeholder="Search in Parts Market" value={{input}}>
        </form>
    </div>
    <div class="w-1/2 flex justify-end">
        <a href="{%url 'partsmarkets:mylist'%}" class="h-full p-3 rounded-lg border border-blue-400 ">My Product</a>
    </div>
</div>
{% endblock search-form %}

{% block content %}
<div class="h-25vh flex justify-evenly">
    {%for photo in product.get_photos%}
    <div class="w-1/3 bg-cover bg-center" style="background-image:url({{photo.file.url}})"></div>
    {%endfor%}
</div>
<div class="justify-center">
    <table class="mx-auto my-12">
        <tr class="border-b border-blue-400">
            <td class="p-3">Product name</td>
            <td class="p-3">{{product.name}}</td>
        </tr>
        <tr class="border-b border-blue-400">
            <td class="p-3">Manufacturer</td>
            <td class="p-3">{{product.maker}}</td>
        </tr>
        <tr class="border-b border-blue-400">
            <td class="p-3">Model</td>
            <td class="p-3">{{product.model_name}}</td>
        </tr>
        <tr class="border-b border-blue-400">
            <td class="p-3">Specification</td>
            <td class="p-3">{{product.spec}}</td>
        </tr>
        <tr class="border-b border-blue-400">
            <td class="p-3">Description</td>
            <td class="p-3">{{product.description}}</td>
        </tr>
        <tr class="border-b border-blue-400">
            <td class="p-3">Quantity</td>
            <td class="p-3">{{product.num_product}}</td>
        </tr>
        <tr class="border-b border-blue-400">
            <td class="p-3">New</td>
            <td class="p-3">{{product.is_new}}</td>
        </tr>
        <tr class="border-b border-blue-400">
            <td class="p-3">Person in charge</td>
            <td class="p-3">{{product.contact_person}}</td>
        </tr>
        <tr class="border-b border-blue-400">
            <td class="p-3">Contact information</td>
            <td class="p-3">{{product.contact_info}}</td>
        </tr>
        <tr>
            <td class="p-3">Price</td>
            <td class="p-3">{{product.price}}</td>
        </tr>
    </table>
</div>
{% if user == product.seller %}
<div class="flex flex-col mx-auto w-1/4 text-center">
    <a class="border border-blue-600 rounded p-4 my-2" href="{% url 'partsmarkets:edit' product.pk%}">Edit</a>
    <a class="border border-red-600 rounded p-4 my-2" href="javascript:delete_stock({{stockinfo.pk}})">Delete</a>
</div>
{% endif %}
<script>
    function delete_stock(pk) {
        if (confirm("Are you sure to delete this item?") == false) {
            return false;
        }
        window.location.href = "{% url 'partsmarkets:delete' product.pk%}";
    }
</script>
{% endblock content %}

templates/partsmarkets/product_list.html
{% extends 'base.html' %}

{% block page_name %}
Parts Market
{% endblock page_name %}

{% block search-form %}
<div class="flex items-center">
    <div class="w-1/2">
        <form class="p-3 w-4/5" action="{%url 'partsmarkets:partsmarket'%}" method="get">
            <input class="search-box placeholder-gray-600" type="text" name="search" id="search"
                placeholder="Search in Parts Market" value={{input}}>
        </form>
    </div>
    <div class="w-1/2 flex justify-end">
        {%if user.is_authenticated%}
        <a href="https://docs.google.com/forms/d/e/1FAIpQLSdlRDbKeVZq3_i--Zn-EbFmuXompGDR_j7-coQrCRGtrpYlPQ/viewform"
            target="_blank" class="h-full p-3 rounded-lg border border-blue-400 ">상품의뢰</a>
        {%endif%}
        <a href="{%url 'partsmarkets:mylist'%}" class="h-full p-3 rounded-lg border border-blue-400 ">My Product</a>
    </div>
</div>
{% endblock search-form %}

{% block content %}
{%if object_list.all%}
<div class="flex flex-wrap">
    {% for product in object_list %}
    {% include 'mixins/product_card.html' with product=product %}
    {% endfor %}
</div>

{% include 'mixins/pagination.html' with page_obj=page_obj %}
{%else%}
{% include 'partials/no_result.html' %}
{%endif%}
{% endblock content %}

templates/partsmarkets/update.html
<span class="truncate">{{product.name}}</span>
<span class="truncate">{{product.maker.name}}</span>
<span class="truncate">{{product.model_name}}</span>
<span class="truncate">{{product.spec}}</span>
<span class="truncate">{{product.is_new}}</span>
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button>submit</button>
</form>